---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
configurations:
  - .transformers.yaml
generators:
  - .ksops.yaml
namespace: peribolos-as-a-service
patchesStrategicMerge:
  - route.yaml
images:
  - name: quay.io/operate-first/peribolos-as-a-service
    newTag: v1.3.0
